//tealium universal tag - utag.43 ut4.0.202207272231, Copyright 2022 Tealium.com Inc. All Rights Reserved.
window.GoogleAnalyticsObject=""||"ga";window[window.GoogleAnalyticsObject]=window[window.GoogleAnalyticsObject]||function(){(window[window.GoogleAnalyticsObject].q=window[window.GoogleAnalyticsObject].q||[]).push(arguments);};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState==='complete'||this.readyState==='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={'view':1,'link':1};u.o=window[window.GoogleAnalyticsObject];u.required={};u.created=false;u.all=function(e,o,v,a,b){for(var i=0;i<u.data.account.length;i++){var t=(u.data.name[i]?u.data.name[i]+".":"");if(o==="event"){u.o(t+e,o,v,a,b)}else if(v){u.o(t+e,o,v)}else{u.o(t+e,o);}}};u.setHitData=function(g,a,b,f){var obj=u.data[a];for(var d in utag.loader.GV(obj)){if(b&&d.indexOf("enh_"+b+"-")!==0&&d.indexOf("enh_all-")!==0){continue;}
var idx=d.split("-")[1],val=obj[d];if(u.typeOf(val)!=="array"){g[idx]=val;}else{g[idx]=val[f];}}};u.addEvent=function(v){if(typeof v.eventCategory=="undefined"||typeof v.eventAction=="undefined"){utag.DB("GA event Category or Action is not set");return;}
if(isNaN(parseInt(v.eventValue))){utag.DB("GA event Value is not a number");v.eventValue=null;}else{v.eventValue=parseInt(v.eventValue)||null;}
u.data.ga_events.push(v);};u.addproduct=function(event_type,len,imp){var g={},i,j,k=[];if(imp===true){k=(u.data.enh_impression_id.length?u.data.enh_impression_id:u.data.enh_impression_name);for(i=0;i<k.length;i++){g={};g.id=(u.data.enh_impression_id[i]?u.data.enh_impression_id[i]:"");g.name=(u.data.enh_impression_name[i]?u.data.enh_impression_name[i]:"");g.brand=(u.data.enh_impression_brand[i]?u.data.enh_impression_brand[i]:"");g.variant=(u.data.enh_impression_variant[i]?u.data.enh_impression_variant[i]:"");g.category=(u.data.enh_impression_category[i]?u.data.enh_impression_category[i]:"");g.list=(u.data.enh_impression_list[i]?u.data.enh_impression_list[i]:"");g.price=(u.data.enh_impression_price[i]?u.data.enh_impression_price[i]:"");g.position=(u.data.enh_impression_position[i]?u.data.enh_impression_position[i]:"");u.setHitData(g,"enhecom_events",event_type,i);u.all('ec:addImpression',g);}}else{for(i=0;i<len;i++){g={};if(u.data.autofill_params==="true"){for(j=0;j<u.data.product_id.length;j++){u.data.product_name[j]=u.data.product_name[j]||u.data.product_id[j];u.data.product_unit_price[j]=u.data.product_unit_price[j]||"1.00";u.data.product_quantity[j]=u.data.product_quantity[j]||"1";}}
g.id=u.data.product_id[i];g.name=(u.data.product_name[i]?u.data.product_name[i]:"");g.brand=(u.data.product_brand[i]?u.data.product_brand[i]:"");g.variant=(u.data.product_variant[i]?u.data.product_variant[i]:"");g.category=(u.data.product_category[i]?u.data.product_category[i]:"");g.price=(u.data.product_unit_price[i]?u.data.product_unit_price[i]:"");g.quantity=(u.data.product_quantity[i]?u.data.product_quantity[i]:"");g.coupon=(u.data.product_discount[i]?u.data.product_discount[i]:"");g.position=(u.data.product_position[i]?u.data.product_position[i]:"");u.setHitData(g,"enhecom_events",event_type,i);u.all('ec:addProduct',g);}}};u.addpromo=function(action,event){var f,g;for(f=0;f<u.data.enh_promo_id.length;f++){g={};g.id=u.data.enh_promo_id[f];g.name=(u.data.enh_promo_name[f]?u.data.enh_promo_name[f]:u.data.enh_promo_id[f]);g.creative=(u.data.enh_promo_creative[f]?u.data.enh_promo_creative[f]:"");g.position=(u.data.enh_promo_position[f]?u.data.enh_promo_position[f]:"");u.all('ec:addPromo',g);}
if(action==="promo_click"&&event==="link"){u.all('ec:setAction',u.data.enh_action);if(u.data.autosend_events==="true"){u.all('send','event','Internal Promotions','click',(g.name?g.name:g.id));}}};u.createTracker=function(){if(u.typeOf(u.data.account)==="string"){u.data.account=u.data.account.replace(/\s/g,"").split(",");}
if(u.typeOf(u.data.name)==="string"&&u.data.name!==""){u.data.name=u.data.name.replace(/\s/g,"").split(",");}
if(!u.data.name||u.data.name.length!==u.data.account.length){var start=u.data.name.length!==u.data.account.length?u.data.name.length:0;tn=utag.tagsettings.gua.trackernames;u.data.name=u.data.name||[];for(i=start;i<u.data.account.length;i++){u.data.name.push("tealium_"+(i+tn));}
utag.tagsettings.gua.trackernames=tn+i;}};u.initTracker=function(){var c;if(!u.created){u.created=true;for(f=0;f<u.data.account.length;f++){c={};if(u.data.clientId){c.storage="none";c.clientId=u.data.clientId;}
if(u.data.siteSpeedSampleRate){c.siteSpeedSampleRate=parseInt(u.data.siteSpeedSampleRate);}
if(u.data.sampleRate){c.sampleRate=parseFloat(u.data.sampleRate);}
c.cookieDomain=u.data.cookieDomain;if(u.data.cookieExpires||u.data.cookieExpires==="0"){c.cookieExpires=parseInt(u.data.cookieExpires);}
if(u.data.legacyCookieDomain){c.legacyCookieDomain=u.data.legacyCookieDomain;}
c.allowLinker=u.data.allowLinker;if(typeof u.data.name[f]!=="undefined"&&u.data.name[f]!==""){c.name=u.data.name[f];}
u.o("create",u.data.account[f],c);}
if(u.data.optimizely==="true"){window.optimizely=window.optimizely||[];window.optimizely.push(['activateUniversalAnalytics']);}}};window.utag.tagsettings=window.utag.tagsettings||{};window.utag.tagsettings.gua=window.utag.tagsettings.gua||{};window.utag.tagsettings.gua.trackernames=window.utag.tagsettings.gua.trackernames||0;u.map={"dom.domain":"cookieDomain,legacyCookieDomain","metrics_user_code":"uid","ga_pagePath":"page","event_name":"eventCategory","link_type":"eventAction","ga_nonInteraction":"nonInteraction","metrics_app_version":"dimension14","last_referrer":"dimension23","bd_suser_provider":"dimension98,dimension96","bd_suser_code":"dimension99,dimension97","clientId":"clientId,dimension94","platform":"dimension36","user_agent":"dimension52","versao_experimento":"dimension17","nome_experimento":"dimension27","link_text":"eventLabel","g_assinatura":"dimension19,dimension95","ua":"tid","metrics_link_target":"pageview-dimension2","metrics_link_view":"pageview-dimension3","metrics_link_offer":"pageview-dimension4","krux_id":"dimension75","ambient":"dimension1","gp_home_tipo_user":"dimension8","gp_home_tipo_hit":"dimension11","dimension28":"dimension28","gp_tenant_jarvis":"dimension29","horizonclientuuid":"dimension76","cp.horizon_id_cookie":"dimension76","cp.krux_id_cookie":"dimension75","ga_eventValue":"eventValue","cesta_assinatura":"dimension21","gp_erro_persona":"dimension31","gp_funil_produtos":"dimension32","gp_perfil_consumo":"dimension35","gp_video_program_id":"dimension113","gp_video_id":"dimension102","pip":"dimension141","gp_service_id":"dimension91","gp_pais_loja":"dimension39","gp_device_browser":"dimension149","hsid":"dimension77"};u.extend=[function(a,b){try{if(1){(function()
{utag.DB("utag_data before merge: ");utag.DB(utag_data);utag.DB("utag.data before merge");utag.DB(utag.data)
utag.ut.merge(utag_data,utag.data);utag.ut.merge(utag.data,utag_data,1);utag.DB("merge done");})()}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){utag.DB("Fetching User Code and User Provider.");let keys=["bd_suser_code","bd_suser_provider","bd_user_autorizador","bd_user_perfilid","bd_user_userid"];utag.DB("Creating request.");let xhr=new XMLHttpRequest();xhr.onload=function(e){let resp=xhr.responseText.split(":");if(resp.indexOf("Error:")>0)return;let obj=Object.fromEntries(keys.map(function(el,index){return[el,!!resp[index]?resp[index]:""];}));utag.DB("Request done. Updating utag.data and utag_data:");utag.DB("utag.data before merging: ");utag.DB(window.utag.data);utag.DB("utag_data before merging: ");utag.DB(window.utag_data);utag.ut.merge(window.utag.data,obj,1);utag.ut.merge(window.utag_data,obj,1);};xhr.open("GET","https://usergate.globo.com",true);xhr.withCredentials=true;xhr.send(null);})();}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){var uaStr=window.navigator.userAgent.toLowerCase(),reTbl=/(tablet|ipad|playbook|silk)|(android(?!.*mobile))/i,reBS=/netcast|smarttv|smart-tv|hbbtv|opera tv|inettv|nettv|nexbox|googletv|apple tv|appletv|pov_tv|android tv|netcast.tv|viera/i,reVG=/xbox|nintendo wii|playstation/i,reMb=/lumia|mobile|ip(hone|od)|android|blackBerry|iemobile|windows phone|j2me|spreadtrum/i,mob=/(?!mobile)/i,testCase="";if(uaStr){b['user_agent']=uaStr;if(reVG.test(uaStr)){testCase="video game";}
else if(reBS.test(uaStr)){testCase="big screen";}
else if(mob.test(uaStr)&&reTbl.test(uaStr)){testCase="tablet";}
else if(reMb.test(uaStr)){testCase="mobile";}
else{testCase="desktop";}}
else{testCase="empty";}
b['platform']=testCase;})();}}catch(e){utag.DB(e)}},function(a,b){(function(d,w){try{var whenAvailableGa=function(callback,trys){var interval=50,dec=trys||5
window.setTimeout(function(){if(window.ga&&window.ga.loaded){callback();}else{if(dec>0){window.setTimeout(arguments.callee,interval);dec--;}}},interval);};whenAvailableGa(function(){for(var iii=0;iii<ga.getAll().length;iii++){ga((function(tr){if(b['cp.GLBID']){tr.set('dimension5','visita');tr.set('dimension6','visitante');}
if(typeof b['metrics_user_services']!=='undefined'){tr.set('dimension10',b['metrics_user_services']);}
if(b['metrics_subset']){tr.set('dimension9',b['metrics_subset']);}
else{tr.set('dimension9',null);}
if(b['metrics_autoplay']){tr.set('dimension7',b['metrics_autoplay'].mode);}
else{tr.set('dimension7',null);}
if(b['metrics_template']){tr.set('dimension16',b['metrics_template']);}
else{tr.set('dimension16',null);}
if(b['metrics_pwa']){tr.set('dimension43',b['metrics_pwa']);}
else{tr.set('dimension43',null);}})(ga.getAll()[iii]));}},20);}
catch(e){}})(document,window);},function(a,b){try{if(1){try{b['ga_pagePath']=b["dom.url"].replace(window.location.protocol+"//","").replace(window.location.hostname,"")}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){if(b["dom.referrer"]){b.last_referrer=b["dom.referrer"];}
else{b.last_referrer="direct";}},function(a,b){try{if(1){var whenAvailable=function(name,callback){var interval=100;window.setTimeout(function(){if(WM[name].length>0){callback(WM[name]);}else{window.setTimeout(arguments.callee,interval);}},interval);};whenAvailable("PlayerManager",function(obj){for(var y=0;y<window.ga.getAll().length;y++){ga((function(tr){if(tr.get("name")==="playerTracker"){tr.set("dimension52",window.utag_data["user_agent"]);tr.set("dimension51",window.utag_data["platform"]);tr.set("dimension22",window.utag_data["bd_suser_code"]);tr.set("dimension21",window.utag_data["bd_suser_provider"]);if(window.utag_data["bd_suser_provider"]==="cadun"){tr.set("$uid",window.utag_data["bd_suser_code"]);}}
else if(tr.get("name")==="productTracker"){tr.set("dimension52",window.utag_data["user_agent"]);tr.set("dimension51",window.utag_data["platform"]);tr.set("dimension99",window.utag_data["bd_suser_code"]);tr.set("dimension98",window.utag_data["bd_suser_provider"]);if(window.utag_data["bd_suser_provider"]==="cadun"){tr.set("$uid",window.utag_data["bd_suser_code"]);}}})(window.ga.getAll()[y]));}});}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(){b.g_assinatura=window.utag_data.g_assinatura;b.bd_suser_code=window.utag_data.bd_suser_code;b.bd_suser_provider=window.utag_data.bd_suser_provider;b.bd_user_autorizador=window.utag_data.bd_user_autorizador;b.bd_user_perfilid=window.utag_data.bd_user_perfilid;b.bd_user_userid=window.utag_data.bd_user_userid;var whenAvailableUtagKey=function(name,callback,trys){var interval=50,dec=trys||5;window.setTimeout(function(){if(window.utag_data[name]){callback(window.utag_data[name]);}else{if(dec>0){window.setTimeout(arguments.callee,interval);dec--;}}},interval);},whenAvailableGa=function(callback,trys){var interval=50,dec=trys||5
window.setTimeout(function(){if(window.ga&&window.ga.loaded){callback();}else{if(dec>0){window.setTimeout(arguments.callee,interval);dec--;}}},interval);};})();}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(d,w){try{var getgaLinker=function(){var linker="";if(typeof window.ga!=="undefined"&&typeof window.ga==="function"&&window.ga.loaded){for(var iii=0;iii<ga.getAll().length;iii++){ga((function(tr){linker=tr.get("linkerParam");})(ga.getAll()[iii]));}}
return linker;},whenAvailableGa=function(callback,trys){var interval=50,dec=trys||5
window.setTimeout(function(){if(window.ga&&window.ga.loaded){callback();}else{if(dec>0){window.setTimeout(arguments.callee,interval);dec--;}}},interval);};whenAvailableGa(function(){var linker=getgaLinker(),productUA="UA-296593-56";window.utag_data.galinker=linker+"&glbproduct="+productUA;},30);}
catch(e){}})(document,window);}}catch(e){utag.DB(e)}},function(a,b){try{if(1){(function(d,w){var getCookie=function(sKey){if(!sKey){return;}
return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null;},removeCookie=function(sKey,sPath,sDomain){if(!getCookie(sKey)){return false;}
document.cookie=encodeURIComponent(sKey)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"");return true;},whenAvailableGa=function(callback,trys){var interval=50,dec=trys||5
window.setTimeout(function(){if(window.ga&&window.ga.loaded){callback();}else{if(dec>0){window.setTimeout(arguments.callee,interval);dec--;}}},interval);},getQueryString=function(field,url){var href=url?url:window.location.href,reg=new RegExp('[?&]'+field+'=([^&#]*)','i'),string=reg.exec(href);return string?decodeURIComponent(string[1]):null;},newTrId=function(len,radix){var chars='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_'.split(''),newId=[],i=0;radix=radix||chars.length;len=len||22;for(i=0;i<len;i++)newId[i]=chars[0|Math.random()*radix];return newId.join('');},trackException=function(exDescription){whenAvailableGa(function(){for(var iii=0;iii<ga.getAll().length;iii++){ga((function(tr){if(tr.get('trackingId')===productUa){tr.send('exception',{'exDescription':exDescription,'exFatal':false});}})(ga.getAll()[iii]));}},20);},productUa=window.utag_data.productGAId,mainDomain=(location.hostname.indexOf('globoi.com')>-1?".globoi.com":".globo.com");whenAvailableGa(function(){var gidTealium=getCookie("gidTealium");if(gidTealium){gidTealium="?"+getCookie("gidTealium").replace(/\"/g,"");var sid=getQueryString('sid',gidTealium),tp=getQueryString('tp',gidTealium),su=getQueryString('su',gidTealium),sa=getQueryString('sa',gidTealium),sae=getQueryString('sae',gidTealium),component=getCookie('glbidTeacomp');for(var iii=0;iii<ga.getAll().length;iii++){ga((function(tr){if(tr.get('trackingId')===productUa){tr.send('event','globoid','login-finish',{'dimension46':sid||'','dimension47':sae||'','dimension48':sa||'','dimension55':sa||'','dimension49':su||'','dimension54':su||'','dimension50':tp||'','dimension56':tp||'','dimension73':component||'','dimension74':component||''});}})(ga.getAll()[iii]));}
var gHostname=(location.hostname.indexOf('globoi')>-1?'login.qa.globoi.com':'login.globo.com');var trID=newTrId(32),prName=su.split(" - ")[0]||"login";ga('create','UA-296593-6','auto','login');ga('login.require','ecommerce');ga('login.set','hostname',gHostname);ga('login.set','page','/finish');ga('login.send','pageview',{'dimension46':sid||'','dimension47':sae||'','dimension48':sa||'','dimension55':sa||'','dimension49':su||'','dimension54':su||'','dimension50':tp||'','dimension56':tp||'','dimension73':component||'','dimension74':component||''});ga('login.ecommerce:addTransaction',{'id':trID,'affiliation':w.location.hostname,'revenue':'0'});ga('login.ecommerce:addItem',{'id':trID,'name':prName,'price':'0','quantity':'1'});ga('login.ecommerce:send');removeCookie('gidTealium','/',mainDomain);removeCookie('glbidTeacomp','/',mainDomain);}},20);w.addEventListener('message',function(event){var gHostname=(location.hostname.indexOf('globoi')>-1?'login.qa.globoi.com':'login.globo.com');if(event.origin.indexOf(gHostname)===-1){return;}
var aurl=(window.location.hostname.indexOf("qa")>-1?"http://usergatedev.cloud.dev.globoi.com":"https://usergate.globo.com");var stUser=JSON.parse(userStorage.utStorage.get("cdUserCodeGlb"));if(!!document.cookie.match(/GLBID=.*?(;|$)/)&&stUser.provider==="anonymous"){cadunUserData(aurl);}
var gidTealium=getCookie("gidTealium");if(gidTealium){gidTealium="?"+getCookie("gidTealium").replace(/\"/g,"");var sid=getQueryString('sid',gidTealium),tp=getQueryString('tp',gidTealium),su=getQueryString('su',gidTealium),sa=getQueryString('sa',gidTealium),sae=getQueryString('sae',gidTealium),component=getCookie('glbidTeacomp');for(var iii=0;iii<ga.getAll().length;iii++){ga((function(tr){if(tr.get('trackingId')===productUa){tr.set({'dimension21':window.utag_data.bd_user_provider||'','dimension22':window.utag_data.bd_user_code||'','dimension96':window.utag_data.bd_user_provider||'','dimension97':window.utag_data.bd_user_code||'','dimension98':window.utag_data.bd_suser_provider||'','dimension99':window.utag_data.bd_suser_code});tr.send('event','globoid','login-finish',{'dimension46':sid||'','dimension47':sae||'','dimension48':sa||'','dimension55':sa||'','dimension49':su||'','dimension54':su||'','dimension50':tp||'','dimension56':tp||'','dimension73':component||'','dimension74':component||''});}})(ga.getAll()[iii]));}
var trID=newTrId(32),prName=su.split(" - ")[0]||"login";ga('create','UA-296593-6','auto','login');ga('login.require','ecommerce');ga('login.set','hostname',gHostname);ga('login.set','page','/finish');ga('login.set',{'dimension21':window.utag_data.bd_user_provider||'','dimension22':window.utag_data.bd_user_code||'','dimension96':window.utag_data.bd_user_provider||'','dimension97':window.utag_data.bd_user_code||'','dimension98':window.utag_data.bd_suser_provider||'','dimension99':window.utag_data.bd_suser_code});ga('login.send','pageview',{'dimension46':sid||'','dimension47':sae||'','dimension48':sa||'','dimension55':sa||'','dimension49':su||'','dimension54':su||'','dimension50':tp||'','dimension56':tp||'','dimension73':component||'','dimension74':component||''});ga('login.ecommerce:addTransaction',{'id':trID,'affiliation':w.location.hostname,'revenue':'0'});ga('login.ecommerce:addItem',{'id':trID,'name':prName,'price':'0','quantity':'1'});ga('login.ecommerce:send');removeCookie('gidTealium','/',mainDomain);removeCookie('glbidTeacomp','/',mainDomain);}
else{trackException('Cookie gidTealium undefined');}},false);})(document,window);}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['ambient']='web'}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){u.o=window[window.GoogleAnalyticsObject];b.ga_events=b.ga_events||[];var c,d,e,f,g,tn,prop;if(u.data&&u.data.name){tn=u.data.name;}
u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"","a":a,"cookieDomain":""||utag.loader.lh(),"name":tn||"","account":"UA-296593-56","anonymizeIp":"false","allowLinker":"true","crossDomainTrack":"produtos.globo.com,login.globo.com,accounts.google.com,especiais.globoplay.globo","enhancedLinkAttribution":"false","enhancedecommerce":"false","displayfeatures":"true","screenView":"false","optimizely":"false","init_before_extensions":"false","autofill_params":"false","autosend_events":"true"||"true","enh_action":"","enh_event_cb":"","enh_checkout_step":"","enh_checkout_option":"","product_action_list":"","product_variant":[],"enh_impression_id":[],"enh_impression_name":[],"enh_impression_price":[],"enh_impression_category":[],"enh_impression_brand":[],"enh_impression_variant":[],"enh_impression_list":[],"enh_impression_position":[],"enh_promo_id":[],"enh_promo_name":[],"enh_promo_creative":[],"enh_promo_position":[],"id":"","product_id":[],"product_name":[],"product_brand":[],"product_category":[],"product_quantity":[],"product_unit_price":[],"product_discount":[],"product_position":[],"ga_events":[],"sessionControl":"","set":{}};if(u.data.init_before_extensions==="true"){u.createTracker();u.initTracker();}
for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("a.")===0){u.data["a"][e[f].substring(2)]=b[d];}else if(e[f].indexOf("set.")===0){u.data.set[e[f].substring(4)]=b[d];}else{u.data[e[f]]=b[d];}}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){u.data.enh_action=u.map[d];}}}}
if(u.typeOf(u.data.ga_events)==="array"&&u.typeOf(b.ga_events)==="array"){if(u.data.ga_events.length===0&&b.ga_events.length>0){u.data.ga_events=b.ga_events;}else if(u.data.ga_events.length>0&&b.ga_events.length>0){u.data.ga_events=u.data.ga_events.concat(b.ga_events);}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_total=u.data.order_total||b._ctotal||"";u.data.order_shipping=u.data.order_shipping||b._cship||"";u.data.order_tax=u.data.order_tax||b._ctax||"";u.data.order_store=u.data.order_store||b._cstore||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";u.data.order_coupon_code=u.data.order_coupon_code||b._cpromo||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_brand.length===0&&b._cbrand!==undefined){u.data.product_brand=b._cbrand.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(u.data.product_discount.length===0&&b._cpdisc!==undefined){u.data.product_discount=b._cpdisc.slice(0);}
if(u.data.init_before_extensions!=="true"){u.createTracker();u.initTracker();}
if(u.data.enhancedecommerce==="true"&&!u.required["ec"]){u.required["ec"]=!0;u.all("require","ec");}
u.data.app_id=u.data.app_id||u.data.appId||b.app_id;u.data.app_name=u.data.app_name||u.data.appName||b.app_name;u.data.app_version=u.data.app_version||u.data.appVersion||b.app_version;u.data.app_rdns=u.data.app_rdns||u.data.appInstallerId||b.app_rdns;u.data.screen_title=u.data.screen_title||u.data.screenName||b.screen_title;if(u.data.app_id||u.data.app_name){g={};g.appName=u.data.app_name;g.appId=u.data.app_id||"";g.appVersion=u.data.app_version;g.appInstallerId=u.data.app_rdns;u.all("set",g);}
u.data.exception_reason=u.data.exception_reason||b.exception_reason;if(u.data.exception_reason){g={};g.exDescription=u.data.exception_reason;g.exFatal=true;u.all("send","exception",g);}
if(u.data.allowLinker==="true"||u.data.allowLinker===true){if(!u.required["linker"]){u.all("require","linker");u.required["linker"]=!0;}
if(u.data.crossDomainTrack){if(u.typeOf(u.data.crossDomainTrack)==="string"){u.data.crossDomainTrack=u.data.crossDomainTrack.replace(/\s/g,'').split(',');}
u.all("linker:autoLink",u.data.crossDomainTrack);}}
if(u.data.anonymizeIp==="true"||u.data.anonymizeIp===true){u.all("set",'anonymizeIp',true);}
if(u.data.uid){u.all("set","&uid",u.data.uid);}
if(u.data.page){u.all("set","page",u.data.page);}
if(u.data.title){u.all("set","title",u.data.title);}
if(u.data.location){u.all("set","location",u.data.location);}
if(u.data.campaignName){u.all("set","campaignName",u.data.campaignName);}
if(u.data.campaignSource){u.all("set","campaignSource",u.data.campaignSource);}
if(u.data.campaignMedium){u.all("set","campaignMedium",u.data.campaignMedium);}
if(u.data.campaignContent){u.all("set","campaignContent",u.data.campaignContent);}
if(u.data.campaignKeyword){u.all("set","campaignKeyword",u.data.campaignKeyword);}
if(u.data.displayfeatures==="true"||u.data.displayfeatures===true){if(!u.required["displayfeatures"]){u.required["displayfeatures"]=!0;u.all("require","displayfeatures");}}
if(u.data.dataSource){u.all("set","dataSource",u.data.dataSource);}
for(prop in utag.loader.GV(u.data.set)){u.all("set",prop,u.data.set[prop]);}
u.data.transaction_events={};u.data.pageview_events={};u.data.link_events={};u.data.enhecom_events={};for(d in utag.loader.GV(u.data)){if(d.indexOf("-")>-1&&(d.indexOf("metric")>-1||d.indexOf("dimension")>-1||d.indexOf("contentGroup")>-1)){if(d.indexOf("transaction-")===0){u.data.transaction_events[d]=u.data[d];}else if(d.indexOf("pageview-")===0){u.data.pageview_events[d]=u.data[d];}else if(d.indexOf("link-")===0){u.data.link_events[d]=u.data[d];}else if(u.data.enhancedecommerce==="true"&&d.indexOf("enh_")===0){u.data.enhecom_events[d]=u.data[d];}}else if(d.indexOf("metric")===0||d.indexOf("dimension")===0||d.indexOf("contentGroup")===0){u.all("set",d,u.data[d]);}}
if(u.data.enhancedLinkAttribution==="true"){if(!u.required["enhancedLinkAttribution"]){u.required["enhancedLinkAttribution"]=!0;u.all("require","linkid","linkid.js");}}
u.data.order_id=(u.data.order_id?u.data.order_id:u.data.id);if(u.data.enhancedecommerce==="true"){u.all("set",'&cu',(u.data.currency?u.data.currency:u.data.order_currency));if(u.data.order_id&&u.data.enh_action==="refund"){if(u.data.order_id instanceof Array&&u.data.order_id.length>0){u.data.order_id=u.data.order_id[0];}
for(f=0;f<u.data.product_id.length;f++){g={};g.id=u.data.product_id[f];g.quantity=(u.data.product_quantity[f]?u.data.product_quantity[f]:"1");u.setHitData(g,"enhecom_events","product_refund",f);u.all('ec:addProduct',g);}
g={};g.id=u.data.order_id;u.setHitData(g,"enhecom_events","refund");u.all('ec:setAction','refund',g);}
else if(u.data.order_id){if(u.data.order_id instanceof Array&&u.data.order_id.length>0){u.data.order_id=u.data.order_id[0];}
u.addproduct("product_purchase",u.data.product_id.length,false);g={};g.id=u.data.order_id;g.affiliation=(u.data.affiliation?u.data.affiliation:u.data.order_store);g.revenue=(u.data.revenue?u.data.revenue:u.data.order_total);g.shipping=(u.data.shipping?u.data.shipping:u.data.order_shipping);g.tax=(u.data.tax?u.data.tax:u.data.order_tax);g.coupon=(u.data.coupon?u.data.coupon:u.data.order_coupon_code);u.setHitData(g,"enhecom_events","purchase");u.all('ec:setAction','purchase',g);}
else if(u.data.enh_action==="product_click"&&u.data.a==="link"){u.addproduct("product_click",1,false);u.all('ec:setAction','click',{list:u.data.product_action_list});if(u.data.autosend_events==="true"){u.all('send','event','UX','click','Results',{'hitCallback':window[u.data.enh_event_cb]});}
}
else if(u.data.enh_action==="detail"){u.addproduct("detail",1,false);g={};u.setHitData(g,"list",u.data.product_action_list);u.all("ec:setAction","detail");}
else if(u.data.enh_action==="add"){u.addproduct("product_add",u.data.product_id.length,false);u.all('ec:setAction','add',{list:u.data.product_action_list});if(u.data.a==="link"&&u.data.autosend_events==="true"){u.all('send','event','UX','click','add to cart');}
}
else if(u.data.enh_action==="remove"){u.addproduct("product_remove",u.data.product_id.length,false);u.all('ec:setAction','remove');if(u.data.a==="link"&&u.data.autosend_events==="true"){u.all('send','event','UX','click','remove from cart');}
}
else if(u.data.enh_action==="checkout"){u.addproduct("product_checkout",u.data.product_id.length,false);g={};g.step=u.data.enh_checkout_step||"1";g.option=u.data.enh_checkout_option;u.all('ec:setAction',u.data.enh_action,g);}
if(u.data.enh_action==="checkout_option"&&u.data.a==="link"){g={};g.step=u.data.enh_checkout_step||"1";g.option=u.data.enh_checkout_option;u.all('ec:setAction',u.data.enh_action,g);if(u.data.autosend_events==="true"){u.all('send','event','Checkout','Option',{'hitCallback':window[u.data.enh_event_cb]});}
}
if(u.data.enh_impression_id){u.addproduct("product_impression",u.data.enh_impression_id.length,true);}
if(u.data.enh_promo_id){u.addpromo(u.data.enh_action,u.data.a);}
g={};if(u.data.order_id){u.setHitData(g,"transaction_events");}
u.setHitData(g,"pageview_events");if(u.data.sessionControl==="start"||u.data.sessionControl==="end"){g.sessionControl=u.data.sessionControl;}
if(u.data.a==="view"){if(u.data.screenView==="true"||u.data.screenView===true){g.screenName=u.data.screen_title||"";u.all("send","screenview",g);}else{g.hitType="pageview";u.all("send",g);}}
}else if(u.data.a==="view"){g={};u.setHitData(g,"pageview_events");if(u.data.sessionControl==="start"||u.data.sessionControl==="end"){g.sessionControl=u.data.sessionControl;}
if(u.data.screenView==="true"||u.data.screenView===true){g.screenName=u.data.screen_title||"";u.all("send","screenview",g);}else{g.hitType="pageview";u.all("send",g);}
if(u.data.order_id&&!(u.data.order_id instanceof Array)){if(!u.required["ecommerce"]){u.required["ecommerce"]=!0;u.all("require","ecommerce","ecommerce.js");}
g={};u.setHitData(g,"transaction_events");g.id=u.data.order_id;g.affiliation=(u.data.affiliation?u.data.affiliation:u.data.order_store);g.revenue=(u.data.revenue?u.data.revenue:u.data.order_total);g.shipping=(u.data.shipping?u.data.shipping:u.data.order_shipping);g.tax=(u.data.tax?u.data.tax:u.data.order_tax);g.currency=(u.data.currency?u.data.currency:u.data.order_currency);u.all('ecommerce:addTransaction',g);for(f=0;f<u.data.product_id.length;f++){g={};g.id=u.data.order_id;g.sku=u.data.product_id[f];g.name=(u.data.product_name[f]?u.data.product_name[f]:u.data.product_id[f]);g.category=(u.data.product_category[f]?u.data.product_category[f]:"");g.price=(u.data.product_unit_price[f]?u.data.product_unit_price[f]:"1.00");g.quantity=(u.data.product_quantity[f]?u.data.product_quantity[f]:"1");u.setHitData(g,"transaction_events");u.all('ecommerce:addItem',g);}
u.all('ecommerce:send');}else if(u.data.order_id instanceof Array&&u.data.order_id.length>0){if(!u.required["ecommerce"]){u.required["ecommerce"]=!0;u.all("require","ecommerce","ecommerce.js");}
var lastindex=0;for(f=0;f<u.data.order_id.length;f++){if(f===u.data.order_id.length-1||(u.data.order_id[f]!==u.data.order_id[f+1])){g={};u.setHitData(g,"transaction_events");g.id=u.data.order_id[f];g.affiliation=(u.data.affiliation&&typeof u.data.affiliation[f]!=="undefined"?u.data.affiliation[f]:u.data.order_store);g.revenue=(u.data.revenue&&typeof u.data.revenue[f]!=="undefined"?u.data.revenue[f]:u.data.order_total);g.shipping=(u.data.shipping&&typeof u.data.shipping[f]!=="undefined"?u.data.shipping[f]:u.data.order_shipping);g.tax=(u.data.tax&&typeof u.data.tax[f]!=="undefined"?u.data.tax[f]:u.data.order_tax);g.currency=(u.data.currency?u.data.currency:u.data.order_currency);u.all('ecommerce:addTransaction',g);for(e=lastindex;e<f+1;e++){g={};g.id=u.data.order_id[f];g.sku=u.data.product_id[e];g.name=(u.data.product_name[e]?u.data.product_name[e]:u.data.product_id[e]);g.category=(u.data.product_category[e]?u.data.product_category[e]:"");g.price=(u.data.product_unit_price[e]?u.data.product_unit_price[e]:"1.00");g.quantity=(u.data.product_quantity[e]?u.data.product_quantity[e]:"1");u.setHitData(g,"transaction_events");u.all('ecommerce:addItem',g);}
lastindex=f+1;}}
u.all('ecommerce:send');}
}
if(u.data.eventCategory&&u.data.eventAction){g={};u.setHitData(g,"link_events");g.hitType="event";g.eventCategory=u.data.eventCategory;if(u.data.nonInteraction){g.nonInteraction=1;}
g.eventAction=u.data.eventAction;if(u.data.eventLabel){g.eventLabel=u.data.eventLabel;}
if(typeof u.data.eventValue!=="undefined"&&u.data.eventValue!==""){g.eventValue=u.data.eventValue;}
if(u.data.screenView==="true"||u.data.screenView===true){g.screenName=u.data.screen_title||"";}
if(u.data.sessionControl==="start"||u.data.sessionControl==="end"){g.sessionControl=u.data.sessionControl;}
u.all("send",g);u.data.eventCategory=u.data.eventAction=u.data.eventLabel=u.data.eventValue="";}
for(e=0;e<u.data.ga_events.length;e++){g={};u.setHitData(g,"link_events");g.hitType="event";g.eventCategory=u.data.ga_events[e].eventCategory;g.eventAction=u.data.ga_events[e].eventAction;g.eventLabel=u.data.ga_events[e].eventLabel;g.eventValue=u.data.ga_events[e].eventValue;if(u.data.ga_events[e].nonInteraction){g.nonInteraction=1;}
if(u.data.sessionControl==="start"||u.data.sessionControl==="end"){g.sessionControl=u.data.sessionControl;}
u.all("send",g);}
if(u.data.socialNetwork&&u.data.socialAction&&u.data.socialTarget){g={};g.hitType="social";g.socialNetwork=u.data.socialNetwork;g.socialAction=u.data.socialAction;g.socialTarget=u.data.socialTarget;u.all("send",g);u.data.socialNetwork=u.data.socialAction=u.data.socialTarget="";}
if(u.data.timingCategory&&u.data.timingVar&&u.data.timingValue){g={};g.hitType="timing";g.timingCategory=u.data.timingCategory;g.timingVar=u.data.timingVar;g.timingValue=u.data.timingValue;g.timingLabel=u.data.timingLabel||"";u.all("send",g);}
if(u.data["ga-disable"]){window["ga-disable-"+u.data["ga-disable"]]=true;}
(function(){var id='tealium-tag-7110';if(document.getElementById(id)){return;}
u.loader({"type":"script","src":'https://www.google-analytics.com/analytics.js',"loc":"script","id":id});u.o.l=1*new Date();})();}};utag.o[loader].loader.LOAD(id);}('43','globo.globoplay'));}catch(error){utag.DB(error);}
