//tealium universal tag - utag.168 ut4.0.202110080222, Copyright 2021 Tealium.com Inc. All Rights Reserved.
window.criteo_q=window.criteo_q||[];try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.isEmptyObject=function(o,a){for(a in o){if(u.hasOwn(o,a)){return false;}}return true;};u.isEmpty=function(o){var t=u.typeOf(o);if(t=="number"){return isNaN(o);}else if(t=="boolean"){return false;}else if(t=="string"){return o.length===0;}else return u.isEmptyObject(o);};u.arrayUnique=function(array){var a=array.concat();for(var i=0;i<a.length;++i){for(var j=i+1;j<a.length;++j){if(a[i]===a[j])a.splice(j--,1);}}return a;};u.ev={"view":1};u.initialized=false;u.scriptRequested=false;u.prep=function(value,alwaysConvert){if(u.typeOf(value)==="string"&&(alwaysConvert||value.indexOf(",")>0)){value=value.replace(/^\s*|\s*$/g,"").split(/\s*,\s*/);}
return value;};u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.copy_ecm_array=function(sourceObj,sourceProp,destObj,destProp){if(!(destObj[destProp]&&u.typeOf(destObj[destProp])=="array"&&destObj[destProp].length>0)){destObj[destProp]=sourceObj[sourceProp].slice(0);}};function _addToEvent(t_criteo_q,ecm){var temp=[],i,j,_prod;for(i=0;i<u.data.event_list.length;i++){_event=u.data.event_list[i];var g=u.data[_event]=(u.data[_event]||{});g.event=_event;_prod=(u.typeOf(g.item)==="object")?Object.create(g.item):{};u.copy_ecm_array(ecm,"product_id",_prod,"id");u.copy_ecm_array(ecm,"product_unit_price",_prod,"price");u.copy_ecm_array(ecm,"product_quantity",_prod,"quantity");_prod.id=_prod.id||0;switch(_event){case"viewItem":case"viewList":case"viewCategory":case"viewSearchResult":if(g.filters){temp=[];for(j=0;j<g.filters.name.length;j++){temp.push({name:g.filters.name[j],operator:g.filters.operator[j],value:(u.typeOf(g.filters.value[j])==="array"?g.filters.value[j].join(", "):g.filters.value[j])});}
g.filters=temp;}
g.item=g.item||_prod.id;break;case"addToCart":case"viewBasket":case"trackTransaction":temp=[];for(j=0;j<_prod.id.length;j++){temp.push({id:_prod.id[j],price:_prod.price[j],quantity:_prod.quantity[j]});}
g.item=temp;if(_event==="trackTransaction"){g.id=g.id||u.data.transaction_id;}
break;}
t_criteo_q.push(u.clearEmptyKeys(g));}}
u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:168");utag.DB(b);var c,d,e,f,h,evt=[],_ecm={};u.data={"base_url":"https://dynamic.criteo.com/js/ld/ld.js?a=##account##","account":"61498","site_type":(function(){return/iPad/.test(navigator.userAgent)?"t":(/Mobile|iP(hone|od)|Android|BlackBerry|IEMobile|Silk/.test(navigator.userAgent)?"m":"d");}()),"order_id":"","product_id":[],"product_quantity":[],"product_unit_price":[],"event_list":[]};var t_criteo_q=[];utag.DB("send:168:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){evt=evt.concat(u.map[d].split(","));}}}}
utag.DB("send:168:MAPPINGS");utag.DB(u.data);if(u.data.cusotmer_id&&!u.data.customer_id){u.data.customer_id=u.data.cusotmer_id}
if(!u.data.account){utag.DB(u.id+": Tag not fired: Required attribute account not populated");return;}
u.data.base_url=u.data.base_url.replace("##account##",u.data.account);u.data.order_id=u.data.order_id||b._corder||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.transaction_id=u.data.transaction_id||u.data.order_id;_ecm.product_id=u.data.product_id;_ecm.product_unit_price=u.data.product_unit_price;_ecm.product_quantity=u.data.product_quantity;if(!u.isEmpty(u.data.account)){t_criteo_q.push({"event":"setAccount","account":u.prep(u.data.account,false)});}else{utag.DB("error:168:Criteo Account ID Missing");return;}
if(!u.isEmpty(u.data.site_type)){t_criteo_q.push({"event":"setSiteType","type":u.data.site_type});}
if(!u.isEmpty(u.data.email)){t_criteo_q.push({"event":"setEmail","email":u.prep(u.data.email,true)});}
if(!u.isEmpty(u.data.hashedEmail)){t_criteo_q.push({"event":"setHashedEmail","email":u.prep(u.data.hashedEmail,true)});}
if(!u.isEmpty(u.data.retailer_visitor_id)){t_criteo_q.push({"event":"setRetailerVisitorId","id":u.prep(u.data.retailer_visitor_id,true)});}
if(!u.isEmpty(u.data.customer_id)){t_criteo_q.push({"event":"setCustomerId","email":u.prep(u.data.customer_id,true)});}
if(!u.isEmpty(u.data.zip_code)){t_criteo_q.push({"event":"setZipcode","zipcode":u.prep(u.data.zip_code,true)});}
u.data.event_list=u.data.event_list.concat(evt);u.data.event_list=u.arrayUnique(u.data.event_list);_addToEvent(t_criteo_q,_ecm);criteo_q.push(t_criteo_q);if(!u.scriptRequested){u.scriptRequested=true;u.loader({"type":"script","src":u.data.base_url,"loc":"script","id":'utag_168'});}
utag.DB("send:168:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("168","globo.globoplay"));}catch(error){utag.DB(error);}
